### ISSUE TITLE
BDD for go

### ISSUE THREAD

**Issue by l3pp4rd** [eduncan911/go-mspec#2]
Have you seen [godog](https://github.com/DATA-DOG/godog)? it is based on Behat and Cucumber and uses gherkin3. You can close this issue, just stumbled on your repository and noticed that it may be helpful, cheers.

**Comment by eduncan911** [comment]
I haven't see that, no.  Looks like a pretty easy format.

I tend to stay away from "runners" though or anything external to what I am working on (flashbacks of .NET test runners and shivers of maintaining that stuff).  I find they tend to take away from my focus - just writing Go code.  Design your software in BDD specs (in code) - implement later.

I actually started out in go using GoConvey to do BDD.  While very cool, I found myself editing to much of the codegen templates and stuff - taking away from my focus of just designing my software.

Hence, this framework: Mspec.  You just spec your framework/code/etc.  No actual Go code implementation and no framework to follow: just design your software.  You are 100% focused on spec'ing your package/code with the fundamentals - without implementing anything.  

I love how I can just dream up anything and design it, with nothing more than a single test file.

```
package bitcoin

import (
  "testing"
  _ "github.com/eduncan911/go-mspec"
)

func Test_Blockchain_Verification(t *testing.T) {

  Given(t, "a duplicate request\nand an existing request already exists", func(when When) {
    
    when("receiving an event", func(it It) {

      it("should reject the event")
      it("should issue a collision event on the bus")
    }
  }
}
```  

Done.  No runners, no text files, nada.  

```
$ go test
Feature: Blockchain verification
  Given a duplicate request
  and an existing request already exists
    When receiving an event
    » It should reject the event «-- NOT IMPLEMENTED
    » It should issue a collision event on the bus «-- NOT IMPLEMENTED
```

I do have some big enhancements coming to this package to help streamline the syntax, making it even simpler without having to remember the `func(when When) {` kind of stuff.
